/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrenarRouteImport } from './routes/entrenar'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ResumenRouteImport } from './routes/resumen'
import { Route as RutinaRouteImport } from './routes/rutina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenarRoute = EntrenarRouteImport.update({
  id: '/entrenar',
  path: '/entrenar',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenRoute = ResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinaRoute = RutinaRouteImport.update({
  id: '/rutina',
  path: '/rutina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrenar': typeof EntrenarRoute
  '/home': typeof HomeRoute
  '/resumen': typeof ResumenRoute
  '/rutina': typeof RutinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrenar': typeof EntrenarRoute
  '/home': typeof HomeRoute
  '/resumen': typeof ResumenRoute
  '/rutina': typeof RutinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrenar': typeof EntrenarRoute
  '/home': typeof HomeRoute
  '/resumen': typeof ResumenRoute
  '/rutina': typeof RutinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entrenar' | '/home' | '/resumen' | '/rutina'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entrenar' | '/home' | '/resumen' | '/rutina'
  id: '__root__' | '/' | '/entrenar' | '/home' | '/resumen' | '/rutina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrenarRoute: typeof EntrenarRoute
  HomeRoute: typeof HomeRoute
  ResumenRoute: typeof ResumenRoute
  RutinaRoute: typeof RutinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenar': {
      id: '/entrenar'
      path: '/entrenar'
      fullPath: '/entrenar'
      preLoaderRoute: typeof EntrenarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen': {
      id: '/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof ResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutina': {
      id: '/rutina'
      path: '/rutina'
      fullPath: '/rutina'
      preLoaderRoute: typeof RutinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrenarRoute: EntrenarRoute,
  HomeRoute: HomeRoute,
  ResumenRoute: ResumenRoute,
  RutinaRoute: RutinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
