/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedEntrenarRouteImport } from './routes/_authenticated/entrenar'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedResumenRouteImport } from './routes/_authenticated/resumen'
import { Route as AuthenticatedRutinaRouteImport } from './routes/_authenticated/rutina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/_authenticated/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntrenarRoute = AuthenticatedEntrenarRouteImport.update({
  id: '/_authenticated/entrenar',
  path: '/entrenar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/_authenticated/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/_authenticated/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumenRoute = AuthenticatedResumenRouteImport.update({
  id: '/_authenticated/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRutinaRoute = AuthenticatedRutinaRouteImport.update({
  id: '/_authenticated/rutina',
  path: '/rutina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/entrenar': typeof AuthenticatedEntrenarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/rutina': typeof AuthenticatedRutinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/entrenar': typeof AuthenticatedEntrenarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/resumen': typeof AuthenticatedResumenRoute
  '/rutina': typeof AuthenticatedRutinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/entrenar': typeof AuthenticatedEntrenarRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/resumen': typeof AuthenticatedResumenRoute
  '/_authenticated/rutina': typeof AuthenticatedRutinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/entrenar'
    | '/home'
    | '/perfil'
    | '/progreso'
    | '/resumen'
    | '/rutina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/entrenar'
    | '/home'
    | '/perfil'
    | '/progreso'
    | '/resumen'
    | '/rutina'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/coach'
    | '/_authenticated/entrenar'
    | '/_authenticated/home'
    | '/_authenticated/perfil'
    | '/_authenticated/progreso'
    | '/_authenticated/resumen'
    | '/_authenticated/rutina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedEntrenarRoute: typeof AuthenticatedEntrenarRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedResumenRoute: typeof AuthenticatedResumenRoute
  AuthenticatedRutinaRoute: typeof AuthenticatedRutinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entrenar': {
      id: '/_authenticated/entrenar'
      path: '/entrenar'
      fullPath: '/entrenar'
      preLoaderRoute: typeof AuthenticatedEntrenarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resumen': {
      id: '/_authenticated/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof AuthenticatedResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rutina': {
      id: '/_authenticated/rutina'
      path: '/rutina'
      fullPath: '/rutina'
      preLoaderRoute: typeof AuthenticatedRutinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedEntrenarRoute: AuthenticatedEntrenarRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedResumenRoute: AuthenticatedResumenRoute,
  AuthenticatedRutinaRoute: AuthenticatedRutinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
